// src/utils/bibliotecaExercicios.js
// Biblioteca padrão de exercícios fisioterapêuticos — carregada no primeiro acesso.
// Cada item: { nome, categoria, descricao, series, repeticoes, frequencia, obs }
// Todos os parâmetros são editáveis depois pelo usuário.

export const BIBLIOTECA_PADRAO = [

  // ── TREINAMENTO MUSCULAR INSPIRATÓRIO ───────────────────────────────────
  { nome: 'TMI com Powerbreathe/Threshold', categoria: 'Treino Muscular Inspiratório',
    descricao: 'Treinamento de força da musculatura inspiratória com carga linear pressórica.',
    series: '3', repeticoes: '10', frequencia: '1-2x/dia', obs: 'Carga a 50% da PImáx, reavaliar semanalmente' },
  { nome: 'TMI endurance', categoria: 'Treino Muscular Inspiratório',
    descricao: 'Treino de resistência inspiratória com carga moderada e maior volume.',
    series: '1', repeticoes: '15-20 min', frequencia: '1x/dia', obs: 'Carga a 30-40% da PImáx' },
  { nome: 'Padrão diafragmático', categoria: 'Treino Muscular Inspiratório',
    descricao: 'Reeducação do padrão respiratório com ênfase na excursão diafragmática, mão no abdome.',
    series: '3', repeticoes: '10 incursões', frequencia: '2x/dia', obs: 'Decúbito dorsal, joelhos fletidos' },
  { nome: 'Inspiração fracionada (em tempos)', categoria: 'Treino Muscular Inspiratório',
    descricao: 'Inspirações nasais fracionadas em 2-3 tempos para recrutamento progressivo.',
    series: '3', repeticoes: '8', frequencia: '2x/dia', obs: '' },

  // ── EXERCÍCIOS RESPIRATÓRIOS ────────────────────────────────────────────
  { nome: 'Respiração com freno labial', categoria: 'Exercícios Respiratórios',
    descricao: 'Expiração contra resistência labial para controle de fluxo e dispneia.',
    series: '3', repeticoes: '10', frequencia: '3x/dia', obs: 'Útil em DPOC e controle de dispneia' },
  { nome: 'Expansão torácica localizada', categoria: 'Exercícios Respiratórios',
    descricao: 'Inspiração profunda direcionada com apoio manual em região torácica específica.',
    series: '3', repeticoes: '10', frequencia: '2x/dia', obs: '' },
  { nome: 'Empilhamento de ar (air stacking)', categoria: 'Exercícios Respiratórios',
    descricao: 'Insuflações sucessivas com ambu/bocal para aumento da capacidade inspiratória.',
    series: '2', repeticoes: '5', frequencia: '2x/dia', obs: 'Doenças neuromusculares' },
  { nome: 'Exercício de débito inspiratório (inspirômetro)', categoria: 'Exercícios Respiratórios',
    descricao: 'Inspirômetro de incentivo a fluxo ou volume para expansão pulmonar.',
    series: '3', repeticoes: '10', frequencia: '3-5x/dia', obs: '' },
  { nome: 'Soluço inspiratório', categoria: 'Exercícios Respiratórios',
    descricao: 'Inspirações curtas e sucessivas para recrutamento de unidades alveolares.',
    series: '3', repeticoes: '5', frequencia: '2x/dia', obs: '' },

  // ── HIGIENE BRÔNQUICA ───────────────────────────────────────────────────
  { nome: 'Ciclo ativo da respiração (CART)', categoria: 'Higiene Brônquica',
    descricao: 'Controle respiratório + expansão torácica + huffing para remoção de secreção.',
    series: '3', repeticoes: 'ciclo completo', frequencia: '2x/dia', obs: '' },
  { nome: 'Drenagem autógena', categoria: 'Higiene Brônquica',
    descricao: 'Respiração em diferentes volumes pulmonares para mobilizar secreção das vias.',
    series: '1', repeticoes: '15-20 min', frequencia: '1-2x/dia', obs: '' },
  { nome: 'Huffing (expiração forçada)', categoria: 'Higiene Brônquica',
    descricao: 'Expiração forçada com glote aberta para deslocar secreção sem broncoespasmo.',
    series: '3', repeticoes: '3-4', frequencia: '2x/dia', obs: '' },
  { nome: 'Oscilação oral de alta frequência (Flutter/Shaker)', categoria: 'Higiene Brônquica',
    descricao: 'Dispositivo de PEP oscilatório para mobilização de secreção.',
    series: '3', repeticoes: '10-15 expirações', frequencia: '2x/dia', obs: '' },

  // ── AERÓBIO ─────────────────────────────────────────────────────────────
  { nome: 'Caminhada em esteira', categoria: 'Aeróbio',
    descricao: 'Treino aeróbio contínuo em esteira com controle de FC e BORG.',
    series: '1', repeticoes: '20-30 min', frequencia: '3-5x/semana', obs: 'Intensidade 60-80% FC reserva ou BORG 11-13' },
  { nome: 'Caminhada ao ar livre', categoria: 'Aeróbio',
    descricao: 'Treino aeróbio em solo, ideal para domiciliar e reabilitação cardíaca.',
    series: '1', repeticoes: '30 min', frequencia: '5x/semana', obs: 'Meta ≥150 min/semana (OMS/AHA)' },
  { nome: 'Cicloergômetro (bicicleta)', categoria: 'Aeróbio',
    descricao: 'Treino aeróbio em bicicleta estacionária com carga progressiva.',
    series: '1', repeticoes: '20-30 min', frequencia: '3-5x/semana', obs: 'Monitorar PA e FC' },
  { nome: 'Treino intervalado (HIIT adaptado)', categoria: 'Aeróbio',
    descricao: 'Alternância de períodos de maior e menor intensidade, conforme tolerância.',
    series: '6-8 blocos', repeticoes: '1 min forte / 2 min leve', frequencia: '2-3x/semana', obs: 'Apenas após liberação e estabilidade clínica' },
  { nome: 'Step / subir e descer degrau', categoria: 'Aeróbio',
    descricao: 'Exercício aeróbio e de potência de MMII usando degrau.',
    series: '3', repeticoes: '2 min', frequencia: '3x/semana', obs: '' },

  // ── FORTALECIMENTO MMII ─────────────────────────────────────────────────
  { nome: 'Agachamento livre', categoria: 'Fortalecimento MMII',
    descricao: 'Fortalecimento de quadríceps, glúteos e cadeia posterior.',
    series: '3', repeticoes: '12', frequencia: '3x/semana', obs: 'Amplitude conforme tolerância articular' },
  { nome: 'Agachamento na cadeira (sentar-levantar)', categoria: 'Fortalecimento MMII',
    descricao: 'Sentar e levantar da cadeira para potência de MMII e funcionalidade.',
    series: '3', repeticoes: '10', frequencia: 'diário', obs: 'Excelente para idosos e domiciliar' },
  { nome: 'Extensão de joelho (cadeira extensora/caneleira)', categoria: 'Fortalecimento MMII',
    descricao: 'Fortalecimento isolado de quadríceps.',
    series: '3', repeticoes: '12', frequencia: '3x/semana', obs: 'Carga progressiva' },
  { nome: 'Flexão de joelho (mesa flexora/caneleira)', categoria: 'Fortalecimento MMII',
    descricao: 'Fortalecimento de isquiotibiais.',
    series: '3', repeticoes: '12', frequencia: '3x/semana', obs: '' },
  { nome: 'Elevação de panturrilha', categoria: 'Fortalecimento MMII',
    descricao: 'Fortalecimento de tríceps sural, importante para retorno venoso e marcha.',
    series: '3', repeticoes: '15', frequencia: '3x/semana', obs: '' },
  { nome: 'Abdução de quadril (faixa elástica)', categoria: 'Fortalecimento MMII',
    descricao: 'Fortalecimento de glúteo médio para estabilidade pélvica.',
    series: '3', repeticoes: '15', frequencia: '3x/semana', obs: '' },
  { nome: 'Ponte de glúteo', categoria: 'Fortalecimento MMII',
    descricao: 'Elevação de quadril em decúbito dorsal para glúteos e cadeia posterior.',
    series: '3', repeticoes: '12', frequencia: '3x/semana', obs: '' },
  { nome: 'Avanço (afundo)', categoria: 'Fortalecimento MMII',
    descricao: 'Passada à frente com flexão de joelhos, fortalecimento unilateral.',
    series: '3', repeticoes: '10 cada perna', frequencia: '3x/semana', obs: '' },
  { nome: 'Leg press', categoria: 'Fortalecimento MMII',
    descricao: 'Fortalecimento global de MMII em aparelho com carga controlada.',
    series: '3', repeticoes: '12', frequencia: '3x/semana', obs: '' },

  // ── FORTALECIMENTO MMSS ─────────────────────────────────────────────────
  { nome: 'Rosca bíceps (halter/faixa)', categoria: 'Fortalecimento MMSS',
    descricao: 'Flexão de cotovelo para fortalecimento de bíceps.',
    series: '3', repeticoes: '12', frequencia: '3x/semana', obs: '' },
  { nome: 'Tríceps na polia/faixa', categoria: 'Fortalecimento MMSS',
    descricao: 'Extensão de cotovelo para tríceps.',
    series: '3', repeticoes: '12', frequencia: '3x/semana', obs: '' },
  { nome: 'Elevação lateral de ombro', categoria: 'Fortalecimento MMSS',
    descricao: 'Abdução de ombro para deltoide, com halter ou faixa.',
    series: '3', repeticoes: '12', frequencia: '3x/semana', obs: 'Cuidado em ombro doloroso' },
  { nome: 'Remada (faixa/halter)', categoria: 'Fortalecimento MMSS',
    descricao: 'Fortalecimento de dorsais e estabilizadores da escápula.',
    series: '3', repeticoes: '12', frequencia: '3x/semana', obs: '' },
  { nome: 'Flexão de braço (adaptada na parede)', categoria: 'Fortalecimento MMSS',
    descricao: 'Push-up adaptado conforme nível funcional, para peitoral e tríceps.',
    series: '3', repeticoes: '10', frequencia: '3x/semana', obs: '' },
  { nome: 'Preensão com bolinha/handgrip', categoria: 'Fortalecimento MMSS',
    descricao: 'Fortalecimento de preensão palmar e antebraço.',
    series: '3', repeticoes: '15', frequencia: 'diário', obs: 'Útil em sarcopenia' },

  // ── EQUILÍBRIO E PROPRIOCEPÇÃO ──────────────────────────────────────────
  { nome: 'Apoio unipodal', categoria: 'Equilíbrio',
    descricao: 'Permanência em apoio de uma perna para treino de equilíbrio estático.',
    series: '3', repeticoes: '30 s cada', frequencia: 'diário', obs: 'Apoio próximo por segurança' },
  { nome: 'Marcha tandem (calcanhar-ponta)', categoria: 'Equilíbrio',
    descricao: 'Caminhada em linha reta com um pé à frente do outro.',
    series: '3', repeticoes: '10 passos', frequencia: 'diário', obs: '' },
  { nome: 'Treino em superfície instável (disco/bosu)', categoria: 'Equilíbrio',
    descricao: 'Equilíbrio dinâmico sobre superfície instável para propriocepção.',
    series: '3', repeticoes: '30 s', frequencia: '3x/semana', obs: '' },
  { nome: 'Transferência de peso látero-lateral', categoria: 'Equilíbrio',
    descricao: 'Deslocamento controlado do peso entre os pés.',
    series: '3', repeticoes: '10 cada lado', frequencia: 'diário', obs: '' },
  { nome: 'Alcance funcional', categoria: 'Equilíbrio',
    descricao: 'Alcançar objetos à frente/lateral mantendo a base, treino de limite de estabilidade.',
    series: '3', repeticoes: '10', frequencia: 'diário', obs: '' },

  // ── MOBILIDADE E ALONGAMENTO ────────────────────────────────────────────
  { nome: 'Alongamento de isquiotibiais', categoria: 'Alongamento',
    descricao: 'Alongamento da cadeia posterior da coxa.',
    series: '3', repeticoes: '30 s', frequencia: 'diário', obs: '' },
  { nome: 'Alongamento de quadríceps', categoria: 'Alongamento',
    descricao: 'Alongamento da face anterior da coxa.',
    series: '3', repeticoes: '30 s cada', frequencia: 'diário', obs: '' },
  { nome: 'Alongamento de peitoral (cantinho)', categoria: 'Alongamento',
    descricao: 'Abertura de peitorais para melhora da mecânica ventilatória e postura.',
    series: '3', repeticoes: '30 s', frequencia: 'diário', obs: 'Bom para padrão respiratório' },
  { nome: 'Mobilidade torácica (rotação)', categoria: 'Alongamento',
    descricao: 'Rotações de tronco para mobilidade da caixa torácica.',
    series: '2', repeticoes: '10 cada lado', frequencia: 'diário', obs: '' },
  { nome: 'Alongamento cervical', categoria: 'Alongamento',
    descricao: 'Alongamento de trapézio superior e musculatura cervical (acessória da respiração).',
    series: '3', repeticoes: '20 s cada lado', frequencia: 'diário', obs: '' },
  { nome: 'Alongamento de panturrilha', categoria: 'Alongamento',
    descricao: 'Alongamento de tríceps sural na parede ou degrau.',
    series: '3', repeticoes: '30 s cada', frequencia: 'diário', obs: '' },

  // ── NEUROFUNCIONAL ──────────────────────────────────────────────────────
  { nome: 'Treino de marcha com obstáculos', categoria: 'Neurofuncional',
    descricao: 'Caminhada transpondo obstáculos para coordenação e dupla tarefa.',
    series: '3', repeticoes: '10 m', frequencia: '3x/semana', obs: 'Reabilitação pós-AVE' },
  { nome: 'Dissociação de cinturas', categoria: 'Neurofuncional',
    descricao: 'Rotação dissociada de cintura escapular e pélvica para controle de tronco.',
    series: '3', repeticoes: '10', frequencia: 'diário', obs: '' },
  { nome: 'Treino de dupla tarefa (cognitivo-motor)', categoria: 'Neurofuncional',
    descricao: 'Atividade motora associada a tarefa cognitiva (contar, falar) simultânea.',
    series: '3', repeticoes: '2 min', frequencia: '3x/semana', obs: '' },
  { nome: 'Alcance e preensão de objetos', categoria: 'Neurofuncional',
    descricao: 'Treino de coordenação motora fina e grossa de MMSS.',
    series: '3', repeticoes: '10', frequencia: 'diário', obs: '' },
  { nome: 'Treino de transferências (sentar-deitar-em pé)', categoria: 'Neurofuncional',
    descricao: 'Treino funcional de mudanças posturais com segurança.',
    series: '3', repeticoes: '5', frequencia: 'diário', obs: '' },

  // ── FUNCIONAL / DOMICILIAR ──────────────────────────────────────────────
  { nome: 'Subir e descer escadas', categoria: 'Funcional',
    descricao: 'Treino de capacidade funcional e potência de MMII em escada real.',
    series: '3', repeticoes: '1 lance', frequencia: 'diário', obs: 'Monitorar dispneia e FC' },
  { nome: 'Levantar do chão', categoria: 'Funcional',
    descricao: 'Treino de descer e levantar do solo, prevenção de quedas em idosos.',
    series: '2', repeticoes: '3', frequencia: '3x/semana', obs: 'Com supervisão' },
  { nome: 'Carregar peso (compras/sacolas)', categoria: 'Funcional',
    descricao: 'Treino funcional de carga relacionado às AVDs.',
    series: '3', repeticoes: '10 m', frequencia: '3x/semana', obs: '' },
  { nome: 'Caminhada com mudança de direção', categoria: 'Funcional',
    descricao: 'Marcha com curvas e giros para agilidade e equilíbrio dinâmico.',
    series: '3', repeticoes: '2 min', frequencia: '3x/semana', obs: '' },
]

// Versão da biblioteca — incrementar para forçar recarga futura
export const BIBLIOTECA_VERSAO = 1
